### ISSUE TITLE
Flywheel: Can framwork signal to stale error after 7 shot balls

### ISSUE THREAD

**Issue by maxeitelwein** [maxeitelwein/frc2020#12]
Reduced error already a bit with changing the ribbon cable

**Comment by Ro5bert** [comment]
Are you sure it's always after 7 balls? Seems arbitrary

**Comment by maxeitelwein** [comment]
Fixed the error. The Sensor was not inverted so the 775s accelerated in positive direction and got negative sensor values. The 775s popped the brakers because they tried to accelerate into infinity
